# API
api_bind = "10.0.0.14"
api_port = 9814
tor_control_port = 9051
onion_hidden_service_port = 9814
tor_support = true

# RPC
# rpc_bind = "127.0.0.1"
# rpc_port = 8814

# bitcoind
btc_network = "mainnet"
btc_rpc_user = "bitcoind.user"
## Notice only user+password **OR** cookie is allowed as rpc auth, any other combination would be rejected
btc_rpc_password = "bitcoind.pass"
btc_rpc_connect = "bitcoind"
btc_rpc_port = 8332

# Flags
debug = false
deps_debug = false
overwrite_key = false

# General
subscription_slots = 10000
subscription_duration = 4320
expiry_delta = 6
min_to_self_delay = 20
polling_delta = 60

# Internal API
internal_api_bind = "127.0.0.1"
internal_api_port = 50051